projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views


app_name = 'recipes'

urlpatterns = [
    path('', views.home, name="home"),
    path('recipes/category/<int:category_id>/',
         views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipe"),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

recipes/views.py
from django.shortcuts import render
from utils.recipes.factory import make_recipe
from .models import Recipe


def home(request):
    recipes = Recipe.objects.all().order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
    })


def category(request, category_id):
    recipes = Recipe.objects.filter(category__id=category_id).order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
    })


def recipe(request, id):
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': make_recipe,
        'is_datail_page': True,
    })

recipes/templates/recipes/pages/home.html
<html lang="en">

{% include 'recipes/partials/head.html' %}

<body>
    {% include 'recipes/partials/header.html' %}
    {% include 'recipes/partials/search.html' %}

    <main class="main-content-container">
        <div class="main-content main-content-list container">
            {% for recipe in recipes %}
                {% include 'recipes/partials/recipes.html' %}
            {% endfor %}
        </div>
    </main>
    {% include 'recipes/partials/footer.html' %}
</body>

</html>

recipes/templates/recipes/pages/recipe-view.html
<html lang="en">

{% include 'recipes/partials/head.html' %}

<body>
    {% include 'recipes/partials/header.html' %}
    {% include 'recipes/partials/search.html' %}

    <main class="main-content-container">
        <div class="main-content main-content-detail container">
            {% include 'recipes/partials/recipes.html' %}
        </div>
    </main>
    {% include 'recipes/partials/footer.html' %}
</body>

</html>

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="https://www.djandoproject.com" target="_blank" rel="noreferrer">By Jadson Silva</a>
    </div>
    <div class="powered">
        <a href="https://www.djandoproject.com" target="_blank" rel="noreferrer">Powered by Django</a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dogs Recipes</title>
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="./assets/images/favicon.png">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/fontawesome.min.css"
        integrity="sha512-UuQ/zJlbMVAw/UU8vVBhnI4op+/tFOpQZVT+FormmIEhRSCnJWyHiBbEVgM4Uztsht41f3FzVWgLuwzUqOObKw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/solid.min.css"
        integrity="sha512-Hp+WwK4QdKZk9/W0ViDvLunYjFrGJmNDt6sCflZNkjgvNq9mY+0tMbd6tWMiAlcf1OQyqL4gn2rYp7UsfssZPA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Remix icons -->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "recipes/css/styles.css" %}">

recipes/templates/recipes/partials/header.html
<!-- Header -->
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a href="{% url 'recipes:home' %}" class="main-logo">
                <i class="fa-solid fa-dog"></i>
                <span class="main-logo-text">Dogs Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-list-cover">
        <img src="https://placehold.co/1280x720.png" alt="Temporario">
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">{{ recipe.title }}</h2>
    </div>
    <div class="recipe-autor">
        <span class="recipe-autor-item">
            <em class="fa fa-user"></em>
            {{ recipe.author.first_name }} {{ recipe.author.last_name }}
        </span>
        <span class="recipe-autor-item">
            <i class="fa-solid fa-calendar"></i>
            {{ recipe.created_at|date:"d/m/y" }} às {{ recipe.created_at|time:"H:i" }}
        </span>
        {% comment %} <span class="recipe-autor-item">
            <i class="fa-solid fa-calendar"></i>
            26/05/2024
        </span> {% endcomment %}
        <span class="recipe-autor-item">
            <a href="/recipes/category/cafe-da-manha/">
                <i class="fa-solid fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
            </a>
        </span>
    </div>
    <div class="recipe-content">
        <p>
            {{ recipe.description }}
        </p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fa-solid fa-stopwatch"></i>Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fa-solid fa-pizza-slice"></i>Porções</h3>
            {{ recipe.servings }} {{ recipe.servings_unit }}
        </div>
    </div>
    <footer class="recipe-footer">
        <a href="/recipes/3/" class="recipe-red-more buttton buttton-dark button-full-width">
            <i class="fa-solid fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
</div>

recipes/templates/recipes/partials/recipes.html
<div class="recipe recipe-list-item">
    <div class="recipe-list-cover">
        <a href="{% url "recipes:recipe" recipe.id %}">
            <img src="{{ recipe.cover.url }}" alt="Temporario">
        </a>
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url "recipes:recipe" recipe.id %}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>
    <div class="recipe-autor">
        <span class="recipe-autor-item">
            <em class="fa fa-user"></em>
            {% if recipe.author.first_name %}
                {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            {% else %}
                {{ recipe.author.username }}
            {% endif %}
        </span>
        <span class="recipe-autor-item">
            <i class="fa-solid fa-calendar"></i>
            {{ recipe.created_at|date:"d/m/y" }} às {{ recipe.created_at|time:"H:i" }}
        </span>
        {% comment %} <span class="recipe-autor-item">
            <i class="fa-solid fa-calendar"></i>
            26/05/2024
        </span> {% endcomment %}
        <span class="recipe-autor-item">
            <a href="{% url "recipes:category" recipe.category.id %}">
                <i class="fa-solid fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
            </a>
        </span>
    </div>
    <div class="recipe-content">
        <p>
            {{ recipe.description }}
        </p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fa-solid fa-stopwatch"></i>Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fa-solid fa-pizza-slice"></i>Porções</h3>
            {{ recipe.servings }} {{ recipe.servings_unit }}
        </div>
    </div>

    {% if is_datail_page is not True %}
    <footer class="recipe-footer">
        <a href="{% url "recipes:recipe" recipe.id %}" class="recipe-red-more buttton buttton-dark button-full-width">
            <i class="fa-solid fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_datail_page is True %}
        <div class="preparation-steps">
            {{ recipe.preparation_steps|linebreaksbr }}
        </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><em class="ri-search-line"></em></button>
        </form>
    </div>
</div>